# Generated by Django 5.1.6 on 2025-02-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_counter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='counter_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
