# Generated by Django 5.1.6 on 2025-02-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_counter_counter_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter',
            old_name='count',
            new_name='value',
        ),
    ]
