# Generated by Django 5.1.6 on 2025-02-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_rename_count_counter_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='counter_id',
        ),
    ]
